# Generated by Django 5.2.10 on 2026-01-27 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Homme'), ('F', 'Femme'), ('O', 'Autre')], default='', max_length=1)),
                ('birth_year', models.PositiveIntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('license_number', models.CharField(blank=True, db_index=True, default='', max_length=50)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='TournamentEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('year', models.PositiveIntegerField(db_index=True, unique=True)),
                ('start_dt', models.DateTimeField(blank=True, null=True)),
                ('end_dt', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams_as_p1', to='core.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams_as_p2', to='core.player')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('player1', models.F('player2')), _negated=True), name='team_players_must_be_different')],
            },
        ),
    ]
