# Generated by Django 5.2.10 on 2026-07-05 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tournamentedition_default_match_duration_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='attitude',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='players/'),
        ),
    ]
