# Generated by Django 5.2.10 on 2026-07-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_player_attitude_player_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='attitude',
        ),
        migrations.AddField(
            model_name='player',
            name='attitudes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
