# Generated by Django 5.2.10 on 2026-01-27 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('GROUP', 'Poule'), ('QF', 'Quart'), ('SF', 'Demi'), ('F', 'Finale')], db_index=True, max_length=10)),
                ('match_format', models.CharField(choices=[('G_SET5_TB44', 'Poule: 1 set à 5, TB à 4-4'), ('QF_SET5_TB44', 'Quart: 1 set à 5, TB à 4-4'), ('NORMAL_1SET', 'Demi: 1 set normal'), ('BO3', 'Finale: 2 sets gagnants')], db_index=True, max_length=20)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Planifié'), ('LIVE', 'En cours'), ('FINISHED', 'Terminé'), ('CANCELED', 'Annulé')], db_index=True, default='SCHEDULED', max_length=15)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('sets_a', models.PositiveIntegerField(default=0)),
                ('sets_b', models.PositiveIntegerField(default=0)),
                ('games_a', models.PositiveIntegerField(default=0)),
                ('games_b', models.PositiveIntegerField(default=0)),
                ('tb_active', models.BooleanField(default=False)),
                ('tb_points_a', models.PositiveIntegerField(default=0)),
                ('tb_points_b', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('court', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='live.court')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='competition.event')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='competition.group')),
                ('side_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_a', to='competition.entry')),
                ('side_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_b', to='competition.entry')),
            ],
            options={
                'ordering': ['event_id', 'scheduled_time', 'order_index', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('side_a', models.F('side_b')), _negated=True), name='match_sides_must_be_different')],
            },
        ),
    ]
