# Generated by Django 5.2.10 on 2026-01-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0002_alter_match_order_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='points_a',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='points_b',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='server',
            field=models.CharField(choices=[('A', 'A sert'), ('B', 'B sert')], default='A', max_length=1),
        ),
    ]
