# Generated by Django 5.2.10 on 2026-01-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0003_match_points_a_match_points_b_match_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='winner_side',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B')], max_length=1, null=True),
        ),
    ]
