# Generated by Django 5.2.10 on 2026-01-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0004_match_winner_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='format',
            field=models.CharField(choices=[('POULE', 'Poule (1 set à 5, TB à 4-4)'), ('QUART', 'Quart (1 set, TB à 4-4)'), ('DEMI', 'Demi (1 set normal)'), ('FINALE', 'Finale (2 sets gagnants)')], default='POULE', max_length=10),
        ),
    ]
