# Generated by Django 5.2.10 on 2026-01-28 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0005_match_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='format',
        ),
    ]
