# Generated by Django 5.2.10 on 2026-01-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0006_remove_match_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_format',
            field=models.CharField(choices=[('G_SET5_TB44', 'Poule: 1 set à 5, TB à 4-4'), ('QF_SET5_TB44', 'Quart: 1 set à 5, TB à 4-4'), ('NORMAL_1SET', 'Demi: 1 set normal'), ('BO3', 'Finale: 2 sets gagnants'), ('MANUAL', 'Manuel (aucune règle auto)')], db_index=True, max_length=20),
        ),
    ]
