# Generated by Django 5.2.10 on 2026-01-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0007_alter_match_match_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='best_of',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='match',
            name='games_to_win',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='match',
            name='tb_at',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='match',
            name='tb_points_to_win',
            field=models.PositiveSmallIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='match',
            name='tb_win_by_two',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_format',
            field=models.CharField(choices=[('G_SET5_TB44', 'Poule: 1 set à 5, TB à 4-4'), ('QF_SET5_TB55', 'Quart: 1 set à 6, TB à 5-5'), ('NORMAL_1SET', 'Demi: 1 set normal'), ('BO3', 'Finale: 2 sets gagnants'), ('MANUAL', 'Manuel (aucune règle auto)')], db_index=True, max_length=20),
        ),
    ]
