# Generated by Django 5.2.10 on 2026-01-29 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
        ('core', '0001_initial'),
        ('live', '0008_match_best_of_match_games_to_win_match_tb_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='edition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tournamentedition'),
        ),
        migrations.AlterField(
            model_name='match',
            name='order_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('edition', 'court', 'order_index'), name='uniq_order_per_edition_court'),
        ),
    ]
