# Generated by Django 5.2.10 on 2026-01-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
        ('core', '0001_initial'),
        ('live', '0009_match_edition_alter_match_order_index_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='match',
            name='uniq_order_per_edition_court',
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('edition', 'order_index'), name='uniq_order_per_edition'),
        ),
    ]
