# Generated by Django 5.2.10 on 2026-01-29 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('live', '0011_backfill_match_edition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tournamentedition'),
        ),
    ]
