# Generated by Django 5.2.10 on 2026-01-29 10:56

from django.db import migrations, models


def forwards(apps, schema_editor):
    Match = apps.get_model("live", "Match")
    Court = apps.get_model("live", "Court")

    central, _ = Court.objects.get_or_create(name="Central")

    # Tous les matchs ordonnés doivent avoir un court
    Match.objects.filter(order_index__isnull=False, court__isnull=True).update(court=central)


def backwards(apps, schema_editor):
    # On ne revient pas en arrière sur les données
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
        ('core', '0001_initial'),
        ('live', '0012_alter_match_edition'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
        migrations.AddConstraint(
            model_name="match",
            constraint=models.CheckConstraint(
                check=models.Q(order_index__isnull=True) | models.Q(court__isnull=False),
                name="court_required_when_ordered",
            ),
        ),
    ]
