# Generated by Django 5.2.10 on 2026-02-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
        ('core', '0001_initial'),
        ('live', '0013_match_court_required_when_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='bracket_slot',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('event', 'stage', 'bracket_slot'), name='uniq_bracket_slot_per_stage_event'),
        ),
    ]
