# Generated by Django 5.2.10 on 2026-02-03 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
        ('core', '0001_initial'),
        ('live', '0014_match_bracket_slot_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='match',
            name='match_sides_must_be_different',
        ),
        migrations.AddField(
            model_name='match',
            name='side_a_label',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='side_b_label',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='side_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_a', to='competition.entry'),
        ),
        migrations.AlterField(
            model_name='match',
            name='side_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_b', to='competition.entry'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('side_a__isnull', True), ('side_b__isnull', True), models.Q(('side_a', models.F('side_b')), _negated=True), _connector='OR'), name='match_sides_must_be_different'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('stage', 'GROUP'), _negated=True), models.Q(('side_a__isnull', False), ('side_b__isnull', False)), _connector='OR'), name='group_matches_require_sides'),
        ),
    ]
