# Generated by Django 5.2.10 on 2026-06-25 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('live', '0016_match_deciding_and_set_scores'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('target_end_time', models.TimeField()),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_days', to='core.tournamentedition')),
            ],
            options={
                'ordering': ['edition', 'date'],
                'unique_together': {('edition', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField()),
                ('duration_min', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=100)),
                ('play_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='live.playday')),
            ],
            options={
                'ordering': ['play_day', 'order_index'],
            },
        ),
    ]
