# Generated by Django 5.2.10 on 2026-06-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0017_playday_break'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_walkover',
            field=models.BooleanField(default=False),
        ),
    ]
