# Generated by Django 5.2.10 on 2026-07-04 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tournamentedition_default_match_duration_min'),
        ('live', '0019_match_stage_p3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='core.tournamentedition')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
