# Generated by Django 5.2.10 on 2026-07-05 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0020_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='match_posters/'),
        ),
        migrations.CreateModel(
            name='PosterJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('RUNNING', 'En cours'), ('DONE', 'Terminé'), ('ERROR', 'Erreur')], db_index=True, default='PENDING', max_length=10)),
                ('error', models.TextField(blank=True, default='')),
                ('attitudes', models.JSONField(blank=True, default=dict)),
                ('candidate_paths', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster_jobs', to='live.match')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
