# Generated by Django 5.2.10 on 2026-07-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0021_match_poster_posterjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='end_reason',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Normale'), ('WALKOVER', 'Forfait'), ('RETIREMENT', 'Abandon')], max_length=10, null=True),
        ),
    ]
