# Generated by Django 5.2.10 on 2026-07-09 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0022_match_end_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='play_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='warmup_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
