# Generated by Django 5.2.10 on 2026-07-14 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0024_backfill_finished_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at']},
        ),
    ]
