# Generated by Django 5.2.10 on 2026-01-27 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('mode', models.CharField(choices=[('S', 'Simple'), ('D', 'Double')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_size_default', models.PositiveIntegerField(default=4)),
                ('qualified_per_group', models.PositiveIntegerField(default=2)),
                ('notes', models.TextField(blank=True, default='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='competition.category')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.tournamentedition')),
            ],
            options={
                'ordering': ['edition__year', 'category__name'],
                'unique_together': {('edition', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_hint', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='core.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='core.team')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='competition.event')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='competition.event')),
            ],
            options={
                'ordering': ['event_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='competition.entry')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='competition.group')),
            ],
        ),
        migrations.CreateModel(
            name='GroupStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=0)),
                ('games_won', models.PositiveIntegerField(default=0)),
                ('games_lost', models.PositiveIntegerField(default=0)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='competition.entry')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='competition.group')),
            ],
            options={
                'ordering': ['group_id', 'rank', '-points', '-games_won'],
            },
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('player__isnull', False), ('team__isnull', True)), models.Q(('player__isnull', True), ('team__isnull', False)), _connector='OR'), name='entry_requires_player_xor_team'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('event', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together={('group', 'entry')},
        ),
        migrations.AlterUniqueTogether(
            name='groupstanding',
            unique_together={('group', 'entry')},
        ),
    ]
