# Generated by Django 5.2.10 on 2026-06-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='withdrawn',
            field=models.BooleanField(default=False),
        ),
    ]
